trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV2@2
  displayName: 'Terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/scripts/infrastructure/K8S'
    backendServiceArm: 'teolia-school-01 (319819ff-ed9b-4c33-a3d3-d7833a1a5a54)'
    backendAzureRmResourceGroupName: 'jaouad-aks-dockercoins'
    backendAzureRmStorageAccountName: 'dockercoinsstorage'
    backendAzureRmContainerName: 'terraform-kubernetes'
    backendAzureRmKey: 'terraform.tfstate'
    

- task: TerraformTaskV2@2
  displayName: 'Terraform destroy'
  inputs:
    provider: 'azurerm'
    command: 'destroy'
    commandOptions: '-auto-approve'
    workingDirectory: '$(System.DefaultWorkingDirectory)/scripts/infrastructure/K8S'
    environmentServiceNameAzureRM: 'teolia-school-01 (319819ff-ed9b-4c33-a3d3-d7833a1a5a54)'
  