apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng-deployment
  namespace: dockercoins
  labels:
    app: rng-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng-app
  template:
    metadata:
      labels:
        app: rng-app
    spec:
      containers:
      - name: rng
        image: jaouadifatssane/rng:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80