apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasher
  name: hasher-svc
  namespace: dockercoins
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hasher-app
  type: ClusterIP