apiVersion: v1
kind: Service
metadata:
  labels:
    app: rng
  name: rng-svc
  namespace: dockercoins
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rng-app
  type: ClusterIP