trigger:
- none

pool:
  vmImage: windows-latest

steps:

- task: TerraformInstaller@0
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV2@2
  displayName: 'initialize Terraform'
  inputs:
    provider: 'azurerm'
    command: 'Init'
    backendServiceArm: 'Azure-teolia-service-connection'
    backendAzureRmResourceGroupName: 'jaouad-aks-dockercoins'
    backendAzureRmStorageAccountName: 'jaouadterraformstorage'
    backendAzureRmContainerName: 'jaouad-terraform-container'
    backendAzureRmKey: 'terraform.tfstate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/scripts/infrastructure'
- task: TerraformTaskV2@2
  displayName: 'Plan Terraform'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/scripts/infrastructure'

- task: TerraformTaskV2@2
  displayName: 'Apply Terraform'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve'
    workingDirectory: '$(System.DefaultWorkingDirectory)/scripts/infrastructure'
