trigger:
- none

pool:
  vmImage: windows-latest

steps:

- task: TerraformInstaller@0
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV2@2
  displayName: 'initialize Terraform'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'teolia-school-01 (319819ff-ed9b-4c33-a3d3-d7833a1a5a54)'
    backendAzureRmResourceGroupName: 'jaouad-aks-dockercoins'
    backendAzureRmStorageAccountName: 'jaouadterraformstorage'
    backendAzureRmContainerName: 'jaouad-terraform-container'
    backendAzureRmKey: 'terraform.tfstate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/scripts/infrastructure'

- task: TerraformTaskV2@2
  displayName: 'Apply Terraform'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'teolia-school-01 (319819ff-ed9b-4c33-a3d3-d7833a1a5a54)'
    workingDirectory: '$(System.DefaultWorkingDirectory)/scripts/infrastructure'
