trigger:
- none

pool:
  vmImage: windows-latest

steps:
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'teolia-school-01 (319819ff-ed9b-4c33-a3d3-d7833a1a5a54)'
    backendAzureRmResourceGroupName: 'jaouad-aks-dockercoins'
    backendAzureRmStorageAccountName: 'jaouadterraformstorage'
    backendAzureRmContainerName: 'jaouad-terraform-container'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'teolia-school-01 (319819ff-ed9b-4c33-a3d3-d7833a1a5a54)'